version: '3.7'
services:
  lyra:
    build:
      context: ./lyra
      dockerfile: Dockerfile
      target: lyra
  lyra-tests:
    build:
      context: ./lyra
      dockerfile: Dockerfile
      target: lyra-tests
  redis:
    build:
      context: ./lyra
      dockerfile: Dockerfile
      target: redis
  flower:
    build:
      context: ./lyra
      dockerfile: Dockerfile
      target: flower
