version: '3.7'
services:
  redis:
    image: swnappdocker.azurecr.io/swn/redis
  lyra:
    image: swnappdocker.azurecr.io/swn/lyra
  lyra-tests:
    image: swnappdocker.azurecr.io/swn/lyra-tests
  flower:
    image: swnappdocker.azurecr.io/swn/flower
