version: '3.7'
services:
  lyra:
    env_file:
      - env.env
      - .env
  lyra-tests:
    env_file:
      - env.env
      - .env
  celeryworker:
    env_file:
      - env.env
      - .env
  flower:
    env_file:
      - env.env
