mnwd: # TODO Remove this and complete the other DT metrics.
  dt_metrics:
    fields:
      - variable: overall_daily_est_outdoor_budget_overage_per_irrig_area
        units: "ccf/acre"
      - variable: overall_daily_est_outdoor_budget_overage_sum
        units: ccf
      - variable: overall_is_in_rebate_program_sum
        units: count
      - variable: overall_rebate_participation_fraction
        units: "count/count"
      - variable: overall_MeterID_count
        units: count

hydstra:
  max_quality_flag: 10

variables:
  rainfall:
    name: Rainfall
    description: Rainfall (inches) as measured at this station or the nearest rainfall gauge.
    variable: rainfall
    source: hydstra
    units: inches
    varfrom: ["11.50"]
    varfrom_fallback: "11" # use min
    varto: "11"
    allowed_aggregations:
      - tot
  discharge:
    name: Discharge
    description: Volumetric discharge (cfs) as measured at this station.
    variable: discharge
    source: hydstra
    units: cfs
    varfrom: ["232.37", "236.34", "232.50"]
    varfrom_fallback: "262" # use min
    varto: "262"
    allowed_aggregations:
      - mean
      - max
      - min
  distance_to_water:
    name: Distance to Water
    description: Distance from sensor to water surface (inches) as measured at this station.
    variable: distance_to_water
    source: hydstra
    units: inches
    varfrom: ["236.34"]
    varfrom_fallback: "236" # use min
    varto: "236"
    allowed_aggregations:
      - mean
      - max
      - min
  raw_level:
    name: Raw Level
    description: Raw Level is the water depth (feet) as measured at this station.
    variable: raw_level
    source: hydstra
    units: feet
    varfrom: ["232.37", "232.50"]
    varfrom_fallback: "232" # use min
    varto: "232"
    allowed_aggregations:
      - mean
      - max
      - min
  conductivity:
    name: Conductivity
    description: Conductivity (µS) as measured at this station.
    variable: conductivity
    source: hydstra
    units: "µS"
    varfrom: ["821.37", "822.37"]
    varfrom_fallback: "821" # use min
    varto: "821"
    allowed_aggregations:
      - mean
      - max
      - min
  urban_drool:
    name: Estimated Urban Drool
    description: Estimate of Monthly Urban Drool (centum cubic feet) accumulated from Regional Subbasins upstream of this station.
    variable: urban_drool
    varfrom: overall_daily_est_outdoor_budget_overage_sum
    source: dt_metrics
    units: ccf
    allowed_aggregations:
      - tot
