# This is a basic workflow to help you get started with Actions

name: "Manual Release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'     
        required: true
        default: 'latest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/checkout@v2
      
      - name: Get Release Tags
        env: 
          TAG: ${{ github.event.inputs.tag }}
          LIBTAG: $(grep __version__ ./lyra/lyra/__init__.py | cut -d '=' -f2 | sed 's/"//g' | tr -d '[:space:]')
        run: echo "$TAG", "$LIBTAG"
          
      
#       - name: Check Release Tags (true)
#         if: contains(env.TAG, env.LIBTAG)
#         run: |
#           echo "$LIBTAG is in $TAG"
      
#       - name: Check Release Tags (false)
#         if: ! contains(env.TAG, env.LIBTAG)
#         run: |
#           echo "$LIBTAG is not in $TAG"
          
          
          
#       - uses: azure/docker-login@v1
#         with:
#           login-server: ${{ secrets.ACR_SERVER }}
#           username: ${{ secrets.ACR_USERNAME }}
#           password: ${{ secrets.ACR_PASSWORD }}
      
#       - name: Build & Push Images
        #run: bash ./scripts/push_release.sh
