name: Manual Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'     
        required: true

jobs:
  manual_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Images
        run: |
          docker -v
          docker-compose -v
          manual_tag=-m${{ github.event.inputs.tag }}
          bash scripts/build_prod.sh -t $manual_tag
          cat docker-stack$manual_tag.yml
          docker-compose -f docker-stack$manual_tag.yml push
          
