name: Push Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on: 
  release:
    types: [created]
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:     
      - uses: actions/checkout@v2
      
      - name: Get Version
        run: |
          LIBTAG=$(grep __version__ ./lyra/lyra/__init__.py | cut -d '=' -f2 | sed 's/"//g' | tr -d '[:space:]')
          echo "libtag=v$LIBTAG" >> $GITHUB_ENV
      
      - name: Print Release Tags 
        run: echo ${{ github.event.release.tag_name }}, $libtag 
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Push Versioned Image and Update Latest
        if: (github.event.release.tag_name == env.libtag)
        run: |
          echo building and pushing versioned and latest images
          echo bash ./scripts/push_release.sh

      - name: Push Tagged Release Image 
        if: (!(github.event.release.tag_name == env.libtag))
        run: |
          echo building and pushing tagged images
          tag=${{ github.event.release.tag_name }}
          echo bash ./scripts/build_prod.sh -t $tag
          echo docker-compose -f docker-stack$tag.yml push
          
