# This is a basic workflow to help you get started with Actions

name: Lint & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches:
      - develop
      - master
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install libspatialindex-dev
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Linters
        run: pip install -r lyra/requirements.txt -r lyra/requirements_test.txt
      - name: Run Linters
        run: bash scripts/lint.sh 
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-stack.yml

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build stack
        run: |
          bash ./scripts/build_dev.sh
          docker-compose up -d lyra-tests
              
      - name: run tests
        run: docker-compose exec -T lyra-tests coverage run --branch -m pytest -sv -m "not integration"
          
      - name: coverage
        run: |
          docker-compose exec -T lyra-tests coverage report -mi
          docker-compose exec -T lyra-tests coverage xml
          docker-compose exec -T lyra-tests cat coverage.xml > coverage.xml
          docker-compose exec -T lyra-tests cat .coverage > .coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
